version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./frontend/src/components:/app/src/components
    networks:
      - gpt-network
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3001

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/src/components:/app/src/components
    networks:
      - gpt-network
    env_file:
      - ./server/.env

networks:
  gpt-network:
    driver: bridge
